[tools]
"github:golangci/golangci-lint" = "2.6.2"
go                              = "1.25.4"
"go:mvdan.cc/sh/v3/cmd/shfmt"   = "3.12.0"
hk                              = "1.25.0"
jq                              = "1.8.1"
markdownlint-cli2               = "0.19.1"
pkl                             = "0.30.0"
prettier                        = "3.7.2"
shellcheck                      = "0.11.0"
taplo                           = "0.10.0"
yamllint                        = "1.37.1"
yq                              = "4.49.2"


[task_config]
includes = ["tasks"]

[tasks.test]
depends     = ["*:test"]
description = "Runs all tests"

[tasks.check]
run = "hk run check"

[tasks."check:all"]
run = "hk run check --all"

[tasks.fix]
run = "hk run fix"

[tasks.ci]
depends     = ["check:all", "test"]
description = "Runs all CI checks - lint and test"
